# Generated by Django 4.0.4 on 2022-05-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("authors", models.CharField(max_length=120)),
                ("acquired", models.BooleanField(default=False)),
                ("published_year", models.DateField()),
            ],
        ),
    ]
