# Generated by Django 4.0.4 on 2022-05-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_year",
            field=models.CharField(max_length=120),
        ),
    ]
