# Generated by Django 4.0.3 on 2022-05-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_published_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_year",
            field=models.IntegerField(),
        ),
    ]
